- name: R
  logo: R
  url: https://www.r-project.org/
  color: 52C0F2
  projects:
    - https://github.com/tychobra/polished
    - https://github.com/jimbrig/jimstools
    - https://github.com/jimbrig/jimstemplates
- name: Google Cloud
  logo: Google Cloud
  url: https://cloud.google.com/
  color: 52C0F2
  projects:
    - https://github.com/tychobra/polished
    - url: https://polished.tech
